### ISSUE TITLE
Increase support for species with. different number of chromosome

### ISSUE THREAD

**Issue by tuannguyen8390** [yekaizhou/duet#3]
Hi team, 

I did check out the Duet preprint, very interesting approach

I've checked out the current algo and seems like the phasing steps were done with 24 chromosomes ?

Is it possible to make some flags to address this ?

Many thanks,

Tuan

**Comment by aquaskyline** [comment]
We are working on enabling more user controls and will release an update soon.

**Comment by yekaizhou** [comment]
Hi,

Duet has been updated that can call all chromosomes and contigs instead of only 24 chromosomes. Please update duet to version 0.4 and add the option '--include_all_ctgs' for your needs.

Thanks,
Yekai
