### ISSUE TITLE
[Enhancement] Sniffles as extra sv_caller 

### ISSUE THREAD

**Issue by tuannguyen8390** [yekaizhou/duet#5]
Hi author team,

I believe it is of interest to add more sv_caller into duet

File `sv_calling.py`, simply inserting:

```
elif caller == 'sniffles':
        os.system('sniffles --input ' + aln_path + ' --reference ' + ref_path + ' --vcf ' + sv_calling_home + 'variants.vcf ' + '--output-rnames' + ' --snf' + sv_calling_home + 'variants.snf ' +  ' -t ' + str(thread) + ' --minsvlen ' + str(svlen_thres) + ' --minsupport ' + str(supp_thres))
```

Obviously, you will need sniffles 2.0.6 install, easily done with `conda install -c bioconda sniffles=2.0.6`. I've made a fork in my local cluster & can make a PR if this is worthwhile considering. 

With Sniffles it is possible to merge the snf file across multiple samples & do joint calling for maximum discovery of SVs in a big cohort (similar with Clair3 GVCF options). But as Duet is developed as an start-to-end pipeline, it is perhaps tricky to deploy in such cases.

---
By the way, cute SV has several recent releases - latest version 2.0.2 so you might want to check that out & update accordingly😃 

Best,

Tuan

**Comment by yekaizhou** [comment]
@tuannguyen8390 Sure, scheduled for next release to include the new versions of Sniffles and cuteSV.

**Comment by yekaizhou** [comment]
duet has been updated to v0.6 to incorporate sniffles2 and cutesv2 as the base sv callers.
