### ISSUE TITLE
Feature enhancement: ability to provide sample name for VCF

### ISSUE THREAD

**Issue by fmobegi** [yekaizhou/duet#7]
It's probably a misguided proposal but is there a way that users can provide a sample_name to be used in place of `SAMPLE` in the vcf files? This becomes handy when merging/concatenating vcf files. I know the files can be preprocessed with `sed` or similar (```cat sample.vcf | sed -e 's/SAMPLE/$filename/'```), but if the variant-calling tools accept a `sample name` options, `duet` will benefit from that.

**Comment by yekaizhou** [comment]
Sure, will add it to our next release.
